### ISSUE TITLE
The excle file is directly converted to the XML file or excle data directly to the table

### ISSUE THREAD

**Issue by ghd258** [syncfusion/Xamarin-FileFormat-Demos#1]
The excle file is directly converted to the XML file or excle data directly to the table

**Comment by MathuMohan** [comment]
**Import data to Excel file:**

Yes, it is possible to export data from an IEnumerable collection to Excel file. Please refer the documentation from the following link.

**UG Link:** [https://help.syncfusion.com/file-formats/xlsio/working-with-data#import-data-from-business-objects](https://help.syncfusion.com/file-formats/xlsio/working-with-data#import-data-from-business-objects) 

**Exporting data from Excel file:**
Currently, it is not available. But we have plans to implement exporting data from an Excel file to IEnumerable collection. For estimation, please create a support incident in our [direct track support system](http://www.syncfusion.com/Account/Logon?ReturnUrl=%2fsupport%2fdirecttrac).
